### ISSUE TITLE
Using this action on other files than README.md

### ISSUE THREAD

**Issue by liperium** [dineshsonachalam/markdown-autodocs#8]
Is there a way to do this action on all my .md files in a repo??

**Comment by dineshsonachalam** [comment]
Please do check this below example. You need to add output file paths option to do markdown-autodocs action on all my .md files.
```
name: markdown-autodocs

on:
  workflow_run:
    workflows:
      - generate-artifacts
    types:
      - completed

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.4
          with:
            #  Optional output file paths, defaults to '[./README.md]'.
            output_file_paths: '[./README.md,./docs/example.md]'
```

**Reference:**
1. https://github.com/dineshsonachalam/repo-using-markdown-autodocs
